import type { ComparableCase, PublicLandPricePoint, TargetLocation } from "./types";

export const targetLocation: TargetLocation = {
  address: "大阪府大阪市都島区都島本通5丁目",
  latitude: 34.7086,
  longitude: 135.5324
};

export const mockTransactionCases: ComparableCase[] = [
  {
    id: "mlit-tx-001",
    source: "mlit_transaction",
    propertyNumber: "XIT001-OSK-001",
    propertyType: "住宅地",
    address: "大阪府大阪市都島区内代町2丁目",
    latitude: 34.7122,
    longitude: 135.5329,
    landAreaM2: 92,
    landAreaTsubo: 27.83,
    priceTotalYen: 54_000_000,
    priceTotalDisplay: "5,400万円",
    unitPricePerM2: 586_957,
    unitPricePerTsubo: 1_940_000,
    zoning: "一住",
    nearestStation: "大阪メトロ谷町線 野江内代",
    access: "徒歩 7分",
    buildingCoverageRatio: 80,
    floorAreaRatio: 300,
    roadCondition: "南 5.4m",
    transactionDate: "2025年第4四半期",
    selected: false,
    externalLink: "https://www.reinfolib.mlit.go.jp/",
    raw: { fallback: true }
  },
  {
    id: "mlit-tx-002",
    source: "mlit_transaction",
    propertyNumber: "XIT001-OSK-002",
    propertyType: "住宅地",
    address: "大阪府大阪市都島区都島北通1丁目",
    latitude: 34.7104,
    longitude: 135.5259,
    landAreaM2: 118,
    landAreaTsubo: 35.69,
    priceTotalYen: 70_500_000,
    priceTotalDisplay: "7,050万円",
    unitPricePerM2: 597_458,
    unitPricePerTsubo: 1_975_000,
    zoning: "近商",
    nearestStation: "大阪メトロ谷町線 都島",
    access: "徒歩 5分",
    buildingCoverageRatio: 80,
    floorAreaRatio: 300,
    roadCondition: "東 6.0m",
    transactionDate: "2025年第3四半期",
    selected: false,
    externalLink: "https://www.reinfolib.mlit.go.jp/",
    raw: { fallback: true }
  },
  {
    id: "mlit-tx-003",
    source: "mlit_transaction",
    propertyNumber: "XIT001-MRG-001",
    propertyType: "宅地",
    address: "大阪府守口市滝井元町3丁目",
    latitude: 34.7244,
    longitude: 135.556,
    landAreaM2: 84,
    landAreaTsubo: 25.41,
    priceTotalYen: 29_800_000,
    priceTotalDisplay: "2,980万円",
    unitPricePerM2: 354_762,
    unitPricePerTsubo: 1_173_000,
    zoning: "二中",
    nearestStation: "京阪本線 滝井",
    access: "徒歩 4分",
    buildingCoverageRatio: 60,
    floorAreaRatio: 200,
    roadCondition: "西 4.0m",
    transactionDate: "2025年第2四半期",
    selected: false,
    externalLink: "https://www.reinfolib.mlit.go.jp/",
    raw: { fallback: true }
  },
  {
    id: "mlit-tx-004",
    source: "mlit_transaction",
    propertyNumber: "XIT001-KIT-001",
    propertyType: "商業地",
    address: "大阪府大阪市北区豊崎6丁目",
    latitude: 34.7142,
    longitude: 135.4998,
    landAreaM2: 146,
    landAreaTsubo: 44.16,
    priceTotalYen: 116_000_000,
    priceTotalDisplay: "1億1,600万円",
    unitPricePerM2: 794_521,
    unitPricePerTsubo: 2_627_000,
    zoning: "準工",
    nearestStation: "大阪メトロ御堂筋線 中津",
    access: "徒歩 10分",
    buildingCoverageRatio: 60,
    floorAreaRatio: 300,
    roadCondition: "南 6.0m",
    transactionDate: "2025年第3四半期",
    selected: false,
    externalLink: "https://www.reinfolib.mlit.go.jp/",
    raw: { fallback: true }
  }
];

export const mockLandPricePoints: PublicLandPricePoint[] = [
  {
    id: "land-osaka-2022",
    source: "mlit_land_price",
    pointId: "大阪都島-1",
    year: 2022,
    standardLotNumber: "都島-1",
    address: "大阪府大阪市都島区都島本通4丁目",
    latitude: 34.7079,
    longitude: 135.5298,
    pricePerM2: 418_000,
    previousYearPricePerM2: 410_000,
    yearOnYearChangeRate: 2,
    cadastral: "住宅地",
    nearestStation: "都島",
    distanceToStation: "600m",
    useCategory: "住宅地",
    buildingCoverageRatio: 80,
    floorAreaRatio: 300,
    raw: { fallback: true }
  },
  {
    id: "land-osaka-2023",
    source: "mlit_land_price",
    pointId: "大阪都島-1",
    year: 2023,
    standardLotNumber: "都島-1",
    address: "大阪府大阪市都島区都島本通4丁目",
    latitude: 34.7079,
    longitude: 135.5298,
    pricePerM2: 432_000,
    previousYearPricePerM2: 418_000,
    yearOnYearChangeRate: 3.3,
    cadastral: "住宅地",
    nearestStation: "都島",
    distanceToStation: "600m",
    useCategory: "住宅地",
    buildingCoverageRatio: 80,
    floorAreaRatio: 300,
    raw: { fallback: true }
  },
  {
    id: "land-osaka-2024",
    source: "mlit_land_price",
    pointId: "大阪都島-1",
    year: 2024,
    standardLotNumber: "都島-1",
    address: "大阪府大阪市都島区都島本通4丁目",
    latitude: 34.7079,
    longitude: 135.5298,
    pricePerM2: 449_000,
    previousYearPricePerM2: 432_000,
    yearOnYearChangeRate: 3.9,
    cadastral: "住宅地",
    nearestStation: "都島",
    distanceToStation: "600m",
    useCategory: "住宅地",
    buildingCoverageRatio: 80,
    floorAreaRatio: 300,
    raw: { fallback: true }
  },
  {
    id: "land-osaka-2025",
    source: "mlit_land_price",
    pointId: "大阪都島-1",
    year: 2025,
    standardLotNumber: "都島-1",
    address: "大阪府大阪市都島区都島本通4丁目",
    latitude: 34.7079,
    longitude: 135.5298,
    pricePerM2: 468_000,
    previousYearPricePerM2: 449_000,
    yearOnYearChangeRate: 4.2,
    cadastral: "住宅地",
    nearestStation: "都島",
    distanceToStation: "600m",
    useCategory: "住宅地",
    buildingCoverageRatio: 80,
    floorAreaRatio: 300,
    raw: { fallback: true }
  },
  {
    id: "land-osaka-2026",
    source: "mlit_land_price",
    pointId: "大阪都島-1",
    year: 2026,
    standardLotNumber: "都島-1",
    address: "大阪府大阪市都島区都島本通4丁目",
    latitude: 34.7079,
    longitude: 135.5298,
    pricePerM2: 489_000,
    previousYearPricePerM2: 468_000,
    yearOnYearChangeRate: 4.5,
    cadastral: "住宅地",
    nearestStation: "都島",
    distanceToStation: "600m",
    useCategory: "住宅地",
    buildingCoverageRatio: 80,
    floorAreaRatio: 300,
    raw: { fallback: true }
  },
  {
    id: "land-moriguchi-2026",
    source: "mlit_land_price",
    pointId: "守口-2",
    year: 2026,
    standardLotNumber: "守口-2",
    address: "大阪府守口市滝井元町3丁目",
    latitude: 34.7248,
    longitude: 135.5568,
    pricePerM2: 318_000,
    previousYearPricePerM2: 308_000,
    yearOnYearChangeRate: 3.2,
    cadastral: "住宅地",
    nearestStation: "滝井",
    distanceToStation: "350m",
    useCategory: "住宅地",
    buildingCoverageRatio: 60,
    floorAreaRatio: 200,
    raw: { fallback: true }
  },
  {
    id: "land-kita-2026",
    source: "mlit_land_price",
    pointId: "大阪北-6",
    year: 2026,
    standardLotNumber: "北-6",
    address: "大阪府大阪市北区豊崎6丁目",
    latitude: 34.7135,
    longitude: 135.5006,
    pricePerM2: 812_000,
    previousYearPricePerM2: 774_000,
    yearOnYearChangeRate: 4.9,
    cadastral: "商業混在住宅地",
    nearestStation: "中津",
    distanceToStation: "850m",
    useCategory: "住宅地",
    buildingCoverageRatio: 60,
    floorAreaRatio: 300,
    raw: { fallback: true }
  }
];

